### ISSUE TITLE
update the mimeo README

### ISSUE THREAD

**Issue by carlost** [steelThread/mimeograph#30]
Discuss the mimeograph:job:completed set and how it should be used.  Clients should check the "completed" set upon connecting to mimeo prior to issuing new jobs.  If necessary we could expand this effort and:
- add a new CLI flag that would cause mimeo to publish the contents of the completed set
- perhaps have mimeo publish the contents of the completed set when a client subscribes

**Comment by elgehelge** [comment]
You can also change `git@github.com:morologous/mimeograph.git` to `git@github.com:steelThread/mimeograph.git` while you are there ;)

**Comment by steelThread** [comment]
Dude, you are like 4 years late.  Are you using this project?

**Comment by elgehelge** [comment]
Haha. Didn't notice that. I was just playing around with it. Is it outdated?

**Comment by steelThread** [comment]
IDK, the technique is still valid.  Probably need to update the external dependencies.

**Comment by morologous** [comment]
Sean,

It's still in production at ITC. Working like a champ.

Jason

**Comment by steelThread** [comment]
That's awesome Jason!  Was such a cool project to work on.
